# TODO: move to pyproject.toml (when implemented)

[tox]
envlist = py{3.7,3.8,3.11}

[testenv]
deps =
    -r dev-requirements.txt

allowlist_externals =
    pydoclint
    mypy

commands =
    ruff format . --check
    ruff check .
    mypy -m git_garden
    python -m pytest
    {[testenv:pydoclint]commands}

[testenv:pydoclint]
basepython = python3.8
commands = pydoclint .
