# TODO: move to pyproject.toml (when implemented)

[tox]
envlist = py{3.7,3.11}

[testenv]
deps =
    -rdev-requirements.txt

allowlist_externals = 
    pydoclint
    mypy

commands = 
    ruff format . --check
    ruff check .
    pydoclint .
    mypy -m git_garden
