name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 0" # weekly CI build

permissions:
  contents: write # required to write back to the repo during tests

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }} # checkout source branch (not detached head)
        fetch-depth: 0 # fetch all history (so non-current branches are available)

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install tox

    - name: Run tox tests
      run: |
        # set git user (required for git authz in tests)
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        # restore main but remain on current branch (assumed to exist in tests)
        git checkout main
        git switch -
        
        # run tests
        tox -e pr
    
    # export results for coverage badge
    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        files: tests/cov.info
        format: lcov

  tag:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: create tag
      run: |
        # fetch the latest tag from the repository
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)

        # if there are no tags, start with v0.0.1
        if [ -z "$LATEST_TAG" ]; then
          NEW_TAG="v0.0.1"
        else
          # split the tag into its components
          IFS='.' read -r -a VERSION_PARTS <<< "${LATEST_TAG:1}"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}

          # increment the patch version
          PATCH=$((PATCH + 1))

          # create the new tag
          NEW_TAG="v$MAJOR.$MINOR.$PATCH"
        fi

        # create and push the new tag
        git tag $NEW_TAG
        git push origin $NEW_TAG

        echo "Created new tag: $NEW_TAG"